### ISSUE TITLE
getTagWeight not being called

### ISSUE THREAD

**Issue by colinbes** [rantecki/docpad-plugin-tagcloud#4]
I am not sure if I am doing something wrong but it doesn't appear as if getTagWeight is being callled when I override the function in docpad.coffee. 

Irrespective of what I override, tag data doesn't change and I assume the default is always running.

I have tried using plugin name 'tagging' and 'tagcloud', code below

```
plugins:
   tagging:
        getTagWeight: (count, maxCount) ->
            return 1+(count/maxCount)
```

and using tagcloud - just in case..

```
plugins:
    tagcloud:
        getTagWeight: (count, maxCount) ->
            return 1+(count/maxCount)
```
